# Site settings
title: hack log
email: piotr.justyna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing, testing, 1, 2, 3...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piotrjustyna.github.io" # the base hostname & protocol for your site
twitter_username: LetZweindaut
github_username: PiotrJustyna

# Build settings
markdown: kramdown
